### PR TITLE
add missing fonts

### PR DESCRIPTION
**Pull request by Musashi-Sakamoto**
Some font files seem to be missing. For example, in fonts.css, there is a code below although there is no font files for fonts specified with `prince-lookup` in **fonts** folder.

```
@font-face {
    font-family: sans-serif; /* Chinese, simplified */
    src: prince-lookup("AR PL UKai CN"), prince-lookup("AR PL KaitiM GB")
}

@font-face {
    font-family: sans-serif; /* Chinese, traditional (TW) */
    prince-font-lang: zh-TW zh-Hant;
    src: prince-lookup("AR PL UKai TW"), prince-lookup("AR PL KaitiM Big5")
}

@font-face {
    font-family: sans-serif; /* Chinese, traditional (HK) */
    prince-font-lang: zh-HK zh-Hant;
    src: prince-lookup("AR PL UKai HK"), prince-lookup("AR PL KaitiM Big5")
}
``` 

### Asana Task
https://app.asana.com/0/1124057801548195/1201443280993946/f

My guess about the cause of this issue is the following.

1. the font specified with `prince-lookup` is missing in Heroku
2. another system font on Heroku server is used
3. the system font above can't support some Chinese Characters
4. some Chinese character is broken on PDF.

Those 2 problems(missing fonts & some Chinese characters not supported) might not be related but it's worth adding missing and checking if this issue is fixed.

reference:
>

prince-lookup()* | Searches for locally installed system fonts, but will also find fonts defined by other @font-face rules. 
-- | --

### CODE REVIEW

**Comment by Musashi-Sakamoto** [comment]
I didn't add already installed fonts.

```
11  is-prince-server   master=  $ heroku run fc-list -a is-prince-se-feat-desig-zgvn2o
 ›   Warning: heroku update available from 7.54.1 to 7.59.2.
Running fc-list on ⬢ is-prince-se-feat-desig-zgvn2o... up, run.9011 (Hobby)
/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf: DejaVu Serif:style=Bold
/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf: DejaVu Sans Mono:style=Book
/usr/share/fonts/type1/gsfonts/n021024l.pfb: Nimbus Roman No9 L:style=Medium Italic
/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf: DejaVu Sans:style=Book
/app/.fonts/Lohit-Tamil.ttf: Lohit Tamil:style=Regular
/usr/share/fonts/type1/gsfonts/n021004l.pfb: Nimbus Roman No9 L:style=Medium
/usr/share/fonts/type1/gsfonts/p052023l.pfb: URW Palladio L:style=Italic
/usr/share/fonts/type1/gsfonts/n022003l.pfb: Nimbus Mono L:style=Regular
/app/.fonts/Lohit-Bengali.ttf: Lohit Bengali:style=Regular
/app/.fonts/kochi-mincho-subst.ttf: Kochi Mincho,東風明朝:style=Regular,標準
/usr/share/fonts/type1/gsfonts/z003034l.pfb: URW Chancery L:style=Medium Italic
/usr/share/fonts/type1/gsfonts/c059013l.pfb: Century Schoolbook L:style=Roman
/usr/share/fonts/type1/gsfonts/d050000l.pfb: Dingbats:style=Regular
/usr/share/fonts/type1/gsfonts/n021023l.pfb: Nimbus Roman No9 L:style=Regular Italic
/usr/share/fonts/type1/gsfonts/n019063l.pfb: Nimbus Sans L:style=Regular Condensed Italic
/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf: DejaVu Sans:style=Bold
/app/.fonts/Lohit-Kannada.ttf: Lohit Kannada:style=Regular
/app/.fonts/AR-PL-SungtiL-GB.ttf: AR PL SungtiL GB,文鼎ＰＬ简报宋:style=Regular
/app/.fonts/Lohit-Devanagari.ttf: Lohit Devanagari:style=Regular
/usr/share/fonts/type1/gsfonts/a010013l.pfb: URW Gothic L:style=Book
/app/.fonts/AR-PL-Mingti2L-Big5.ttf: AR PL Mingti2L Big5,文鼎ＰＬ細上海宋:style=Reguler,Regular
/app/.fonts/Lohit-Punjabi.ttf: Lohit Punjabi:style=Regular
/usr/share/fonts/type1/gsfonts/n019064l.pfb: Nimbus Sans L:style=Bold Condensed Italic
/usr/share/fonts/type1/gsfonts/p052004l.pfb: URW Palladio L:style=Bold
/app/.fonts/OpenSymbol.ttf: OpenSymbol:style=Regular
/usr/share/fonts/type1/gsfonts/n022023l.pfb: Nimbus Mono L:style=Regular Oblique
/usr/share/fonts/type1/gsfonts/a010015l.pfb: URW Gothic L:style=Demi
/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf: DejaVu Sans Mono:style=Bold
/usr/share/fonts/type1/gsfonts/n019043l.pfb: Nimbus Sans L:style=Regular Condensed
/app/.fonts/Lohit-Oriya.ttf: Lohit Oriya:style=Regular
/app/.fonts/Lohit-Telugu.ttf: Lohit Telugu:style=Regular
/usr/share/fonts/type1/gsfonts/n019044l.pfb: Nimbus Sans L:style=Bold Condensed
/app/.fonts/Arial.ttf: Arial:style=Regular,Normal,obyčejné,Standard,Κανονικά,Normaali,Normál,Normale,Standaard,Normalny,Обычный,Normálne,Navadno,thường,Arrunta
/usr/share/fonts/type1/gsfonts/a010033l.pfb: URW Gothic L:style=Book Oblique
/usr/share/fonts/type1/gsfonts/n021003l.pfb: Nimbus Roman No9 L:style=Regular
/usr/share/fonts/type1/gsfonts/s050000l.pfb: Standard Symbols L:style=Regular
/usr/share/fonts/type1/gsfonts/b018035l.pfb: URW Bookman L:style=Demi Bold Italic
/usr/share/fonts/type1/gsfonts/c059033l.pfb: Century Schoolbook L:style=Italic
/app/.fonts/UnBatang.ttf: UnBatang,은 바탕:style=Regular
/usr/share/fonts/type1/gsfonts/a010035l.pfb: URW Gothic L:style=Demi Oblique
/app/.fonts/Garuda.ttf: GARUDA:style=Regular
/app/.fonts/Lohit-Gujarati.ttf: Lohit Gujarati:style=Regular
/app/.fonts/UKaiTW.ttf: AR PL UKai TW:style=Book
/usr/share/fonts/type1/gsfonts/n019023l.pfb: Nimbus Sans L:style=Regular Italic
/usr/share/fonts/type1/gsfonts/b018012l.pfb: URW Bookman L:style=Light
/usr/share/fonts/type1/gsfonts/c059016l.pfb: Century Schoolbook L:style=Bold
/usr/share/fonts/type1/gsfonts/n022004l.pfb: Nimbus Mono L:style=Bold
/usr/share/fonts/type1/gsfonts/n019024l.pfb: Nimbus Sans L:style=Bold Italic
/app/.fonts/Lohit-Malayalam.ttf: Lohit Malayalam:style=Regular
/usr/share/fonts/type1/gsfonts/b018032l.pfb: URW Bookman L:style=Light Italic
/usr/share/fonts/type1/gsfonts/p052003l.pfb: URW Palladio L:style=Roman
/app/.fonts/UKaiCN.ttf: AR PL UKai CN:style=Book
/app/.fonts/kochi-gothic-subst.ttf: Kochi Gothic,東風ゴシック:style=Regular,標準
/usr/share/fonts/type1/gsfonts/n019004l.pfb: Nimbus Sans L:style=Bold
/usr/share/fonts/type1/gsfonts/b018015l.pfb: URW Bookman L:style=Demi Bold
/usr/share/fonts/type1/gsfonts/n022024l.pfb: Nimbus Mono L:style=Bold Oblique
/usr/share/fonts/type1/gsfonts/c059036l.pfb: Century Schoolbook L:style=Bold Italic
/usr/share/fonts/type1/gsfonts/p052024l.pfb: URW Palladio L:style=Bold Italic
/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf: DejaVu Serif:style=Book
/app/.fonts/UKaiTWMBE.ttf: AR PL UKai TW MBE:style=Book
/app/.fonts/UKaiHK.ttf: AR PL UKai HK:style=Book
/app/.fonts/UnDotum.ttf: UnDotum,은 돋움:style=Regular
/usr/share/fonts/type1/gsfonts/n019003l.pfb: Nimbus Sans L:style=Regular
```

**Review by juan-invoicesimple — COMMENTED** [review]
how can we make sure this fixes the problem?

**Comment by TrangNguyenISBC** [comment]
> how can we make sure this fixes the problem?

Great question @juan-invoicesimple. I think it would be easier to check if @Musashi-Sakamoto can add some pictures of the pdf file before this fix and after this fix.

**Comment by Musashi-Sakamoto** [comment]
@TrangNguyenISBC @juan-invoicesimple 
On Heroku, it uses **ShanHeiSun-Light** , which doesn't support the character.
[Image from Gyazo](https://gyazo.com/66a97eb756b6d9d5fddd5f5b261c30e9)

On local, for the *滙* (U+6ED9) , I could confirm that **LiSongPro** supports the character.
So I added the font as a fallback.
9f576421905e3c048ce7da0393b9cc1e

**Comment by Musashi-Sakamoto** [comment]
@juan-invoicesimple cc: @TrangNguyenISBC 
The fix is confirmed on PDF downloaded from staging. UMingCN is one of the the newly added fonts
[Image from Gyazo](https://gyazo.com/a1b0e2f92e160bc48c83536048b9558d)

**Review by juan-invoicesimple — COMMENTED** [review]
if we only need this font, why are you adding more?
can it be any copyright problem with this font?

**Comment by TrangNguyenISBC** [comment]
I think this PR tries to add all the missing fonts. Let's make it clearer by adding detailed description on:
- What exact font need to be added to fix the error in Asana task?
- What is nice-to-have fonts that can prevent us from receiving error reports from users, and for which specific language. For example: Japanese: font A, font B.
Sorry for require much information, just want to clarify and make sure that we don't bother the font/language that are running well now. Thanks @Musashi-Sakamoto for great investigation.

**Comment by Musashi-Sakamoto** [comment]
@juan-invoicesimple

> if we only need this font, why are you adding more?
> can it be any copyright problem with this font?

Thank you for your insights.
Seems like some of the fonts I added on this PR didn't have free license. I will add 1 free font that would solve this issue right now.

 @TrangNguyenISBC 

> What exact font need to be added to fix the error in Asana task?
> What is nice-to-have fonts that can prevent us from receiving error reports from users, and for which specific language. For example: Japanese: font A, font B.
> Sorry for require much information, just want to clarify and make sure that we don't bother the font/language that are running well now. Thanks @Musashi-Sakamoto for great investigation.

Thank you for your insights.
So far the bug I found is one specific Chinese character.
I downloaded "Noto Serif SC" from google fonts and that solves the problem. Maybe I could add that one for now and if any other font bugs are caught by users, we can tackle then.
I think it's good idea to add a font just to solve the issue instead of adding all the missing fonts in order to lower the risk.

**Comment by juan-invoicesimple** [comment]
Lets just fix this issue and then we can check how necessary is to add the others

**Comment by Musashi-Sakamoto** [comment]
> Lets just fix this issue and then we can check how necessary is to add the others

That's a good idea! I already updated the PR @juan-invoicesimple 

[Image from Gyazo](https://gyazo.com/fbe52d24b1f7bd66d583cbdff5d518f1)

**Review by juan-invoicesimple — APPROVED** [review]
great job @Musashi-Sakamoto 👍

**Pull request merged**
